---
- name: '{{ (state == "stopped") | ternary ("Stop", "Start") }} {{ myloader_stop_programs }}'
  systemd:
    name: '{{ item }}'
    state: '{{ state }}'
  loop: '{{ myloader_stop_programs }}'
  become: yes